### ISSUE TITLE
clear() not fully clearing the screen

### ISSUE THREAD

**Issue by therladbsgh** [trystan/AsciiPanel#1]
When clear() is executed, the screen does not completely get cleared; the contents of the "cleared screen" becomes translucent into the background, which obscures any other objects that are displayed later in the screen.

Upon close inspection of the code, it appears that "oldBackgroundColors" and "oldForegroundColors" may be causing this issue, as these are not present in older versions (which does not have this problem) and perfectly describes this issue (the current foreground and background blends with the old foreground and background.)

**Comment by anubiann00b** [comment]
Wait why did you close this...?

**Comment by therladbsgh** [comment]
I found that this problem was fixed in commit 94c4774e5391aff8381758661ea4a388c3843665 ("Fix for Linux machines following the advice on ...") For some reason the "download-zip" button on Github kept downloading the previous version from commit 6bb5921a91181fbd8c74f6f0e661c35feab26d17 ("Always repaint"), which led me to encounter this error.
