### ISSUE TITLE
AsciiPanel Constructor

### ISSUE THREAD

**Issue by Gloomshroud** [trystan/AsciiPanel#14]
Greetings! While attempting your roguelike tutorial (excellent work, btw!), I was [working on part 01](http://trystans.blogspot.com.br/2011/08/roguelike-tutorial-01-java-eclipse.html) with the simple setup. The line: 

`terminal = new AsciiPanel();`

is where I believe the constructor is being called - but I'm a noob and could be utterly incorrect. I was looking at the front page of this repo and noticed the nifty feature of being able to change among various sized CP437 and Dwarf Fortress Tileset fonts. However, when I gleefully plugged in 

`terminal = new AsciiPanel(80, 24, AsciiFont.DRAKE_10x10);`

Eclipse started to yell at me about how _AsciiFont cannot be resolved to a variable_ and I became sad. So, I tearfully cracked open your JAR file (which I conveniently downloaded right from the tutorial [and then added as a referenced external library in Eclipse] because Maven, Ant, Gradle and all that stuff makes my brain explode. Big mess. Wife hates it. 

Anywho, after opening the JAR, I began to peruse the code. I found the first constructor, and a second which takes two integers for modifying the window's size...but there is no third constructor that takes an AsciiFont argument. In fact, I could find no references to AsciiFont anywhere! But that's strange, since I definitely see the class in this very repo! Maybe it's some of that fancy obfuscation stuff? I don't know...but either way, I can't use the tool as intended (either through ignorance or bug has yet to be determined). 

One thing of some small importance might be added. The JAR file itself seems to only have been update as of 3 years ago, whereas the latest commits have happened literally within hours of this posting. Am I using a deprecated version of the tool?

Now, this is likely me being a dumb noob, but I figured I'd check anyway! Am I missing something obvious for which you will all likely laugh at me? Or is this a nefarious plot by the reptiloid overlords to thwart my attempts at becoming a heroic programmer of mighty mightiness? 

If it turns out that there is such an issue, maybe I can figure out how to build my own JAR using the files provided without Maven or any of that stuff. 

_Nota Bene_: I know that most developers like to keep stuff succinct and to the point and free of any repartee. I am not most developers. I'm not even a developer, really. Just trying to be. I am, however, a writer. :)

**Comment by Gloomshroud** [comment]
Or, I could just open my terminal and type 

`sudo apt-get install maven`

Download this thingy as a ZIP, extract it, and then do...

`mvn install`

And finally go to the directory indicated in the last line to find it...

I thought that would be a lot harder...

**Comment by trystan** [comment]
Yeah. The jar from the tutorial is what I used when making the tutorial - ages and ages ago. I don't know of a good way to keep the tutorial up to date with the code and other improvements others have pointed out. It sounds like you got it figured out though.

**Comment by Gloomshroud** [comment]
Yessir, sure did. The only thing I could think of is to plop all that code on here and let those who wish to contribute their ideas via pull requests and the like. Thank you for noticing anyway! It seems my noob was showing...my apologies.
