### ISSUE TITLE
No Licence Given

### ISSUE THREAD

**Issue by bhelyer** [trystan/AsciiPanel#2]
AsciiPanel has no licence attached, so it can't be distributed with anything.

**Comment by anubiann00b** [comment]
Oh man. I've used this library a ton and I never even noticed :P. This is a pretty big issue...

**Comment by trystan** [comment]
Oh yeah. I always forget that. What's a good "do whatever you want" license?

**Comment by TyphoidTony** [comment]
Possibly the MIT license?

**Comment by bhelyer** [comment]
Yeah, something light like MIT would be good.

**Comment by trystan** [comment]
I added the MIT license. Let me know if there's anything else I should do (tags, releases, etc) with this.

**Comment by anubiann00b** [comment]
Perfect! I think this can be closed now.
